
services:
  web:
    build: .
    volumes:
      - ./test123:/app/test123
      - ./locale:/app/locale
      - ./logs:/app/logs
    ports:
      - "8888:8888"
    environment:
      - LANG=es_ES.UTF-8
      - LC_ALL=es_ES.UTF-8